In [1]:
import numpy as np


In [2]:
print(np.__version__)

1.21.5


In [3]:
a=np.arange(2,10)#creates numpy array using .arange() functions
print(type(a))

<class 'numpy.ndarray'>


In [4]:
b=np.array([1,2,3,4])# creating numpy array using np.array() function
print(type(b))

<class 'numpy.ndarray'>


In [5]:
m=np.linspace(1,3,15)#creating numpy array using linspace to generate15 equally spaced points from 1 to 3
m

array([1.        , 1.14285714, 1.28571429, 1.42857143, 1.57142857,
       1.71428571, 1.85714286, 2.        , 2.14285714, 2.28571429,
       2.42857143, 2.57142857, 2.71428571, 2.85714286, 3.        ])

In [9]:
c=np.arange(4).reshape(2,2)
m=np.ones((2,3))
print(c)
np.matmul(c,m)

[[0 1]
 [2 3]]


array([[1., 1., 1.],
       [5., 5., 5.]])

In [10]:
c.sum(axis=0)

array([2, 4])

In [11]:
a[a%2==1]#getting all odd numbers from the array
c[c%2==1]#getting all odd numbers from the array

array([1, 3])

In [16]:
a[a%2==1]= -1 # replacing values based on some conditions
a

array([-1, -1,  4, -1,  6, -1,  8, -1])

In [17]:
a
# create a copy of the original array using the copy() method
copied_array = a.copy()
# modify the copied array
copied_array[0] = 10
# print the original and copied arrays
print(a)  # array('i', [1, 2, 3, 4, 5])
print(copied_array)    # array('i', [10, 2, 3, 4, 5])

[-1 -1  4 -1  6 -1  8 -1]
[10 -1  4 -1  6 -1  8 -1]


In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack([a,b])

In [ ]:
np.hstack([a,b])

In [18]:
a = np.array([1,2,3])
np.hstack((np.repeat(a, 6), np.tile(a, 3)))

array([1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 1, 2, 3, 1,
       2, 3, 1, 2, 3])

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

In [ ]:
arr = np.arange(9).reshape(3,3)

print('Original array')
print(arr)

# Solution

print("\nModified array")
arr[:,]

In [ ]:
#create numpy array with random  float numbers between 5 and 10 
import random
d=np.random.random((5,10))
np.set_printoptions(threshold=4)
d

In [ ]:
#two ways of computing aggregate functions from numpy array 
a.mean()
np.mean(a)


In [ ]:
np.isnan(a).any()#to check if any null value exists in the numpy arrray

In [ ]:
bins = np.array([0, 3, 5, 7])
inds = np.digitize(a.astype('float'), bins)
np.set_printoptions(threshold=1)
#print(inds)
labels = {1:'small', 2: 'medium', 3:'large'}
iris_cat_data = [labels[x] for x in inds]
iris_cat_data[:10]

In [19]:
a = np.arange(6.0)
print(a)
np.split(a, [4, 5, 6, 7])

[0. 1. 2. 3. 4. 5.]


[array([0., 1., 2., 3.]),
 array([4.]),
 array([5.]),
 array([], dtype=float64),
 array([], dtype=float64)]

In [ ]:
pip install numexpr

# Numexpr is a Python library that provides fast numerical expression evaluation in Python. It is designed to speed up numerical computations by optimizing and accelerating arithmetic operations on large arrays and matrices.

## Numexpr achieves this by allowing the evaluation of numerical expressions that can be compiled to machine code using efficient CPU and memory utilization. This enables Numexpr to perform complex computations on large datasets more efficiently than traditional Python methods.

In [ ]:
import numexpr as ne
import timeit

In [ ]:
%%timeit -n200 -r10
ne.evaluate("m+c")

In [ ]:
%%timeit -n200 -r10
m+c

In [ ]:
#to check if two numpy arrays are equal
array1 = np.array([0.12,0.17,0.24,0.29])
array2 = np.array([0.12,0.19,0.26,0.31])
array1==array2

In [ ]:
np.allclose(array1,array2,0.1)
np.allclose(array1,array2,0.2)


In [ ]:
x = np.array([3, 17, 14, 23, 2, 2, 6, 8, 1, 2, 16, 0])
np.clip(x,2,5)#Given an interval, values outside the interval are clipped to the interval edges.np.clip()
#is used to add lower and upper limit to the array


In [20]:
#using where as if else condition 
y = np.array([1,5,6,8,1,7,3,6,9])
np.where(y>5,"Miss","Hit")


array(['Hit', 'Hit', 'Miss', 'Miss', 'Hit', 'Miss', 'Hit', 'Miss', 'Miss'],
      dtype='<U4')